import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header.js";
import Footer from "@/components/Footer.js";

export default function About() {
  return (
    <>
      <Head>
        <title>ChapterWise - About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="about-us-container">
          <h1>About us</h1>
          <h2>We don’t summarize chapters.</h2>
          <p>We help you pass exams.</p>
          <p>
            Textbooks aren’t written for exams — they’re written to be complete.
            </p>
            <p>
            That’s the problem. 
            </p>
            <p>
            Students are expected to read hundreds of pages, figure out what matters, and somehow turn it into exam-ready knowledge. Most don’t know <span className="bold">what to focus on</span>, what to <span className="bold">ignore</span>, or how deep they’re expected to understand each topic. 
            </p>
            <p>That’s where <span className="bold">ChapterWise</span> comes in.
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
