import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header.js";
import Footer from "@/components/Footer.js";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowUpFromBracket } from "@fortawesome/free-solid-svg-icons";
import { faCopy as faCopyRegular } from "@fortawesome/free-regular-svg-icons";
import {
  faCopy as faCopySolid,
  faCheck,
} from "@fortawesome/free-solid-svg-icons";

export default function App() {
  const [text, setText] = useState("");
  const [textareaActive, setTextareaActive] = useState(false);
  const [aiOutput, setAiOutput] = useState("");
  const [isAiOutput, setIsAiOutput] = useState(false);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleSummarize = async () => {
    if (!text.trim()) {
      setAiOutput("Please paste some text before generating notes.");
      setIsAiOutput(false); // not AI output
      return;
    }

    // Validation: maximum length (e.g., 50,000 characters)
    const minLength = 1000; // minimum characters for a chapter
    if (text.length < minLength) {
      setAiOutput(
        `Chapter is too short. Minimum length is ${minLength} characters.`
      );
      return;
    }

    // Validation: maximum length (e.g., 50,000 characters)
    const maxLength = 50000;
    if (text.length > maxLength) {
      setAiOutput(
        `Chapter is too long. Please split it into smaller sections (max 50,000 characters).`
      );
      return;
    }

    setLoading(true); // show loading
    setAiOutput(""); // clear previous output

    try {
      let userId = localStorage.getItem("userId");
      if (!userId) {
        userId = crypto.randomUUID(); // generate a unique id
        localStorage.setItem("userId", userId);
      }

      const res = await fetch("http://localhost:5000/api/generate-notes", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ text, userId }),
      });

      if (res.status === 429) {
        const data = await res.json();
        setAiOutput(data.error); // show daily limit message
        setIsAiOutput(false); // backend error
      } else if (!res.ok) {
        setAiOutput("Error: Could not generate notes.");
      } else {
        const data = await res.json();
        setAiOutput(data.output);
        setIsAiOutput(true); // this is actual AI output
      }
    } catch (err) {
      console.error(err);
      setAiOutput("Error: Could not connect to server.");
      setIsAiOutput(false);
    } finally {
      setLoading(false);
      setText("");
    }
  };

  // copy to clipboard output
  const handleCopy = () => {
    if (!aiOutput) return;

    navigator.clipboard.writeText(aiOutput); // copy to clipboard
    setCopied(true);

    setTimeout(() => {
      setCopied(false); // revert after 5-10 seconds
    }, 5000); // 5000ms = 5 seconds
  };

  const handleReset = () => {
  setText("");        // clears the input
  setAiOutput("");    // clears the output
  setLoading(false);  // reset loading state if needed
};

  return (
    <>
      <Head>
        <title>ChapterWise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="app-container">
          {!aiOutput && (
            <>
              <h1 className="app-h1">
                Turn chapters into{" "}
                <span className="highlight">exam-ready notes instantly</span>
              </h1>
              <p className="app-p">
                Paste your chapter or upload a file, and get clear, exam-ready
                notes in seconds.
              </p>
              <div className="textarea-wrapper">
                <label htmlFor="chapterTextarea" className="sr-only"></label>
                <textarea
                  id="chapterTextarea"
                  value={text}
                  onChange={(e) => setText(e.target.value)}
                  onFocus={() => setTextareaActive(true)}
                  onBlur={() => setTextareaActive(false)}
                  placeholder="Paste your chapter here…"
                ></textarea>
                {!text && !textareaActive && (
                  <>
                    <button className="upload-button">
                      <FontAwesomeIcon
                        className="upload-icon"
                        icon={faArrowUpFromBracket}
                      />
                      Upload chapter
                    </button>

                    <p className="files-allowed">pdf, word, ppt, txt</p>
                  </>
                )}
              </div>
              {/* character count */}
              {/* Validation: check text length, prevent empty submission. */}
              {/* file upload (PDF, DOCX) support. */}
              <button
                onClick={handleSummarize}
                disabled={loading}
                className="app-button"
              >
                {loading ? "Creating your notes..." : "Create My Notes"}
              </button>{" "}
            </>
          )}
          {/* Disabled while AI is processing */}
          {/* Show a spinner or “Generating notes…” message while API call is in progress. */}
          {/* Error message handling (e.g., network errors, API errors). */}
          {aiOutput && (
            <>
              <p className="output-success-message">Your notes are ready!</p>
              <pre className="ai-output">
                {aiOutput || "Output will appear here..."}
              </pre>
              <button
                onClick={handleCopy}
                disabled={!aiOutput || !isAiOutput}
                className="copy-button"
              >
                {copied ? (
                  <>
                    <FontAwesomeIcon icon={faCheck} className="copied-icon" />
                    <span className="copied-text">copied</span>
                  </>
                ) : (
                  <>
                    <FontAwesomeIcon
                      icon={faCopyRegular}
                      className="copy-icon"
                    />
                    <span className="copy-text">copy</span>
                  </>
                )}
              </button>
              <div>
              <button onClick={handleReset} className="back-button">
                Summarize another chapter
              </button>
              </div>
            </>
          )}
        </div>
      </main>
      <Footer />
    </>
  );
}
