import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header.js";
import Footer from "@/components/Footer.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>ChapterWise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="landing-container">
          <p className="tagline1">Read less. Remember more.</p>
          <h1 className="headline">
            Turn textbook chapters into exam-ready notes
          </h1>
          <p className="sub-headline">
            Upload a chapter. Get clear, structured notes made for exams.
          </p>
          <a href="/app" className="cta-app">
            Summarize a chapter
          </a>
          <p className="tagline2">Designed for undergraduate exams</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
