import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header.js";
import Footer from "@/components/Footer.js";

export default function About() {
  return (
    <>
      <Head>
        <title>ChapterWise - Terms & Privacy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="terms-privacy-container">
          <h1>Terms & Privacy</h1>
          <h2>Terms of Service</h2>
          <p className="numbered-list">1. Acceptance of Terms</p>
          <p>
            By using ChapterWise, you agree to comply with these Terms of
            Service. If you do not agree, please do not use the website or app.
          </p>
          <p className="numbered-list">2. Use of the Service</p>
          <p>
            ChapterWise provides generated study notes for personal
            educational use. You may not use the service for commercial
            purposes, plagiarism, or distributing content that violates any
            laws.
          </p>
          <p className="numbered-list">3. User Responsibility</p>
          <p>
            You are responsible for the accuracy and legality of any content you
            submit. ChapterWise is not responsible for errors in uploaded
            chapters or misuse of generated notes.
          </p>
          <p className="numbered-list">4. Intellectual Property</p>
          <p>
            All generated notes and materials remain property of ChapterWise.
            Users may use the notes for personal study purposes only.
            Redistribution, resale, or commercial use is prohibited.
          </p>
          <p className="numbered-list">5. Account & Security</p>
          <p>
            If you create an account, you are responsible for keeping your login
            credentials secure. Notify us immediately if you suspect
            unauthorized access.
          </p>
          <p className="numbered-list">6. Changes to Terms</p>
          <p>
            ChapterWise may update these terms at any time. Continued use of the
            service constitutes acceptance of any changes.
          </p>
          <h2 className="privacy-policy-h2" id="privacy-policy">Privacy Policy</h2>
          <p className="numbered-list">1. Information We Collect</p>
          <p>
            We may collect information you provide, such as account details,
            uploaded chapters, and usage data to improve the service.
          </p>
          <p className="numbered-list">2. How We Use Your Data</p>
          <p>
            Your data is used to generate study notes, improve the service,
            and provide a better user experience.
          </p>
          <p className="numbered-list">3. Data Sharing</p>
          <p>
            We do not sell or share your uploaded chapters or personal
            information with third parties, except as required by law.
          </p>
          <p className="numbered-list">4. Security</p>
          <p>
            We use reasonable technical measures to protect your data, but no
            method is completely secure. Upload only content you are comfortable
            sharing.
          </p>
          <p className="numbered-list">5. Retention</p>
          <p>
            Uploaded chapters and generated notes are stored temporarily to
            process requests. Long-term copies are not kept unless stored in
            your account.
          </p>
          <p className="numbered-list">6. Cookies & Tracking</p>
          <p>
            ChapterWise may use cookies for session management and analytics
            purposes only.
          </p>
          <p className="numbered-list">7. User Rights</p>
          <p>
            You may request deletion of your account or any stored data by
            contacting us at{" "}
            <a href="mailto:support@chapterwise.com">support@chapterwise.com</a>
            .
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
